---
linters:
  AllowedScriptType:
    enabled: true
    allowed_types:
      - text/javascript
      - application/ld+json
  ClosingErbTagIndent: { enabled: true }
  CommentSyntax: { enabled: true }
  ErbSafety: { enabled: true }
  FinalNewline: { enabled: true }
  NoJavascriptTagHelper: { enabled: true }
  ParserErrors: { enabled: true }
  RightTrim: { enabled: true }
  SelfClosingTag: { enabled: true }
  SpaceAroundErbTag: { enabled: true }
  SpaceIndentation: { enabled: true }
  SpaceInHtmlTag: { enabled: true }
  TrailingWhitespace: { enabled: true }
