---
linters:
  AllowedScriptType: { enabled: true }
  ClosingErbTagIndent: { enabled: true }
  CommentSyntax: { enabled: true }
  ErbSafety: { enabled: true }
  FinalNewline: { enabled: true }
  NoJavascriptTagHelper: { enabled: true }
  ParserErrors: { enabled: true }
  RightTrim: { enabled: true }
  SelfClosingTag: { enabled: true }
  SpaceAroundErbTag: { enabled: true }
  SpaceIndentation: { enabled: true }
  SpaceInHtmlTag: { enabled: true }
  TrailingWhitespace: { enabled: true }
